### ISSUE TITLE
Implement Global Navigation

### ISSUE THREAD

**Issue by MaxwellKendall** [roblherron/react_gallery_app#2]
As a user I want to be able to click a tab and navigate from one url to the next

# Acceptance Criteria (A/C)
1. the root url is `/search` instead of `/`
2. If you go to `/` it automatically redirects you to `/search`

**Comment by MaxwellKendall** [comment]
@roblherron RE: [Git Branching](https://www.atlassian.com/git/tutorials/using-branches)

Please create a new branch and push your commits to it instead of `master`.

We're going to use a naming convention for our branches as follows:

-  bugs are prefixed with `bugs/`
-  features are prefixed with `ftr/`

so your branch should be: `ftr/gh-2/global-navigation`

```shell
git checkout -b ftr/gh-2/global-navigation
```

**Comment by MaxwellKendall** [comment]
@roblherron RE [Redirecting urls](https://reactrouter.com/web/api/Redirect)

**Comment by roblherron** [comment]
Took care of these details.
